[package]
name = "akstorytowiki-wasm-bindings"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
akstorytowiki = { git = "https://github.com/enokiun/akstorytowiki", version = "0.1.0" }
wasm-bindgen = "=0.2.105"
